#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld(features='cxx cxxstlib',
        source='test_main.cc',
        target='test_main',
        use=['3rd-party'])

    bld(features='cxx cxxprogram',
        source='pivoting.cc',
        target='run_tests',
        use=['project-headers', '3rd-party', 'TRNG', 'OpenMP', 'test_main'])
    
