#! /usr/bin/env python
# encoding: utf-8

def build(bld):
  bld(features = 'cxx cxxprogram',
      source   = 'tim.cc',
      target   = 'tim',
      use = [ 'project-headers', '3rd-party', 'SPDLOG', 'TRNG', 'OpenMP' ])

  bld(features = 'cxx cxxprogram',
      source   = 'imm.cc',
      target   = 'imm',
      use = [ 'project-headers', '3rd-party', 'SPDLOG', 'TRNG', 'OpenMP' ])

  bld(features = 'cxx cxxprogram',
      source   = 'simulator.cc',
      target   = 'simulator',
      use = [ 'project-headers', '3rd-party', 'SPDLOG', 'TRNG', 'OpenMP', 'JSON' ])
